# Generated by Django 4.0.3 on 2022-04-04 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_deporte', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIndumentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_indumentaria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200)),
                ('stock', models.IntegerField(max_length=11)),
                ('tipo_deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTiendaDeportiva.tipodeporte')),
                ('tipo_indumentaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTiendaDeportiva.tipoindumentaria')),
            ],
        ),
    ]
